repos:
-   repo: local
    hooks:
    -   id: push-all-submodules
        name: "Push all submodules to remote"
        entry: ./scripts/push_all_submodules.sh
        language: system
        stages: [pre-commit]
        always_run: true

    -   id: convert-obsidian-links
        name: "Convert Obsidian links to CDN links"
        entry: python scripts/convert_links.py
        language: python
        types: [markdown]
        stages: [pre-commit]

    -   id: upload-excalidraw-svgs
        name: "Upload Excalidraw SVGs to GitHub image repo"
        entry: ./scripts/upload_excalidraw_svgs.sh
        language: system
        stages: [pre-commit]
        always_run: true